#include "app_internal.h"

BridgeClient bridge;
Widget status_label;
Widget volume_popup;
Widget volume_button;
Widget position_scale;
Widget play_pause_button;
Widget browser_list_scroller;
Widget browser_list_canvas;
Widget source_list_widget;
Widget list_frame;
Widget artwork_label;
Widget main_artwork_label;
Widget album_grid;
Widget album_grid_scroller;
Widget grid_view_button;
Widget album_tracks_popup;
Widget album_tracks_title;
Widget album_tracks_list;
Widget sidebar_frame;
Widget sidebar_sizer;
Widget right_pane_widget;
Widget browser_widget;
Widget search_widget;
Pixmap artwork_pixmap = XmUNSPECIFIED_PIXMAP;
Pixmap main_artwork_pixmap = XmUNSPECIFIED_PIXMAP;
Pixmap shuffle_list_pixmap = XmUNSPECIFIED_PIXMAP;
Pixmap repeat_list_pixmap = XmUNSPECIFIED_PIXMAP;
Pixmap automix_list_pixmap = XmUNSPECIFIED_PIXMAP;
Pixmap autoplay_list_pixmap = XmUNSPECIFIED_PIXMAP;
ButtonIconState button_icons[12];
unsigned int button_icon_count;
Pixmap album_grid_pixmaps[100];
unsigned int album_grid_pixmap_count;
int browser_mode;
unsigned int album_grid_columns = 1;
int album_grid_origin_x = 8;
int album_grid_timer_pending;
char album_popup_catalog_ids[100][256];
char album_popup_kinds[100][32];
unsigned int album_popup_count;
int player_is_playing;
double player_duration;
unsigned int player_poll_count;
XtIntervalId player_poll_timer = (XtIntervalId)0;
int prior_position_percent = -1;
int shutting_down;
char current_view_path[512] = "/v1/listen-now";
char populated_view_path[512];
char current_view_type[32] = "songs";
char current_view_heading[512] = "Listen Now";
char current_view_container_kind[32];
char current_view_ids[100][256];
char current_view_catalog_ids[100][256];
char current_view_item_kinds[100][32];
char current_view_labels[100][1200];
char current_view_titles[100][512];
char current_view_artists[100][512];
unsigned int current_view_durations[100];
int current_view_is_current[100];
int current_view_is_autoplay[100];
char current_view_artwork_urls[100][1024];
unsigned int current_view_disc_numbers[100];
unsigned int current_view_track_numbers[100];
int current_view_container_rows[100];
char source_paths[107][512];
char source_titles[107][512];
unsigned int source_count;
int sidebar_drag_start_x;
Dimension sidebar_drag_start_width;
unsigned int sidebar_artwork_size = 160;
int now_playing_source_visible;
unsigned int visible_to_model[100];
unsigned int visible_view_count;
char current_filter[256];
unsigned int current_view_count;
unsigned int current_render_limit = 30;
int current_view_is_track_detail;
int current_view_collapsed;
int list_lazy_loading;
int browser_scroll_last_value = -1;
int browser_scroll_redraw_from = -1;
int browser_scroll_redraw_to = -1;
int browser_scroll_redraw_pending;
XtIntervalId browser_resize_redraw_timer = (XtIntervalId)0;
int volume_popup_visible;
int volume_icon_level = -1;
int player_shuffle_enabled;
int player_repeat_mode;
int player_automix_enabled;
int player_autoplay_enabled;
int rendered_shuffle_state = -1;
int rendered_repeat_mode = -1;
int rendered_automix_state = -1;
int rendered_autoplay_state = -1;
int browser_list_selected_model = -1;
int browser_list_last_click_model = -1;
Time browser_list_last_click_time;
XtAppContext application_context;
